version: '3'
services:
  api:
    build: .
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/test
    volumes:
      - .:/usr/src
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo
