version: '2'
services:
  db:
    image: mongo
  api:
    build: .
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://db:27017/test
    volumes:
      - .:/classmere_api
    ports:
      - "5000:5000"
    depends_on:
      - db
  scraper:
    image: rutgerfarry/scraper
    environment:
      - MONGO_URL=mongodb://db:27017/test
    depends_on:
      - db
